config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :profiles
  resources :posts
  resources :friends
  resources :friendships, only: [:create, :destroy, :update, :index]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create]

  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
    unauthenticated :user do
      root 'users/registrations#new', as: :unauthenticated_root
    end
  end

  get "/auth/google_oauth2/callback", to: "omniauth_callbacks#google"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :profile
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user

end

app/models/google_account.rb
class GoogleAccount < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :profile
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :profile

  has_many :comments
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :posts
  has_many :likes

  has_many :comments, through: :posts
  has_one_attached :avatar
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  has_many :posts, through: :profile

  has_many :friendships
  has_one :google_account

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_create do |user|
      user.name = auth.info.first_name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    
  end

  def create
    @comment = Comment.new(body: params[:body], profile_id: params[:profile_id], post_id: params[:post_id] ).save
    # redirect_back(fallback_location:"/")
    redirect_to url:"/posts##{params[:post_id]}"
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!

  def index
    @profiles = Profile.where.not(id: current_user.profile.id).shuffle
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def index
    @fri = Friendship.where(user_id: current_user.id).where(confirmed: 0)
    @fri_inv = Friendship.where(friend_id: current_user.id).where(confirmed: 0)
  end

  def create
    @fri = current_user.friendships.build
    @fri.friend_id = params[:friend_id]
    @fri.confirmed = 0

    if @fri.save
      flash[:notice] = "Friend request sent!"
    else
      flash[:notice] = "Some errors!"
    end

    redirect_back(fallback_location:"/")
  end

  def update
    @fri_inv = Friendship.where(user_id: params[:id]).where(friend_id: current_user.id).first
    @fri_inv.confirmed = 1
    @fri_inv.save

    flash[:notice] = "Friend request accepted!"
    redirect_back(fallback_location:"/")
  end

  def destroy
    @fri = Friendship.where(user_id: current_user.id).where(friend_id: params[:id])
    @fri_inv = Friendship.where(user_id: params[:id]).where(friend_id: current_user.id)
    
    @fri.delete_all
    @fri_inv.delete_all

    flash[:notice] = "Unfriend done."
    redirect_back(fallback_location:"/")
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.profile_id = params[:profile_id]
    @like.post_id = params[:post_id]
    @like.save
    redirect_back(fallback_location:"/")
  end

  def destroy
    Like.where(profile_id: current_user.profile.id).where(post_id: params[:id]).delete_all
    redirect_back(fallback_location:"/")
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def google

		@user = User.from_omniauth(request.env["omniauth.auth"])
          
    prof = Profile.new
    prof.name = @user.name
    prof.user_id = @user.id
    prof.save

		sign_in_and_redirect @user

    # user = User.from_omniauth(env["omniauth.auth"])
    # session[:user_id] = user.id
    # redirect_to root_path, notice: "Login successful!"

    # acc = Current.user.google_accounts.where(email: auth.info.email).first_or_initialize
    # acc.update(
    #   name: auth.info.first_name,
    #   token: auth.credentials.token
    # )

    # redirect_to root_path, notice: "Login successful!"
  end

  # def auth
  #   request.env["omniauth.auth"]
  # end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new
  end

  def new
    @post = current_user.posts.build
  end

  def show
    @post = Post.find(params[:id])

    
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_back(fallback_location:"/")
    else 
      flash[:notice] = "Some errors!"
      render :new, status: :unprocessable_entity
    end

  end

  private

  def post_params
    params.require(:post).permit(:body, :profile_id)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]
  before_action :authenticate_user!


  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
    @profile = Profile.find(params[:id])
    @post = Post.new
    @posts = Post.where(profile_id: params[:id]).order(created_at: :desc)

    @fri = Friendship.where(user_id: current_user.id).where(friend_id: params[:id])
    @fri_inv = Friendship.where(user_id: params[:id]).where(friend_id: current_user.id)
    @friends = true if @fri.present? || @fri_inv.present?

    fri_c = @fri.where(confirmed: 1)
    fri_inv_c = @fri_inv.where(confirmed: 1)
    @confirmed = true if fri_c.present? || fri_inv_c.present?
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:name, :interests, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/friendships/index.html.erb
<% if @fri_inv.count > 0 %>
  <h3> New friend requests! </h3>
  <ul>
    <% @fri_inv.each do |f| %>
      <li>
        <%= link_to User.find(f.user_id).profile.name, profile_path(f.user_id), class: "profile-link", style: "font-size:24px;" %>
      </li>
    <% end %>
  </ul>
<% end %>

<br />

<% if @fri.count > 0 %>
  <h4> Pending friend response</h4>
  <ul>
    <% @fri.each do |f| %>
      <li>
        <%= link_to User.find(f.friend_id).profile.name, profile_path(f.friend_id), class: "profile-link", style: "font-size:24px;" %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/posts/index.html.erb
<div class="postsindex">
  
  <div data-turbolinks="false">
    <%= form_with model: @post, class: "post-input" do |form| %> 
      <%= form.text_field :body, placeholder: "Anything brewing?", class: "form-control", style: "width: 32rem; height: 38px;" %>
      <%= form.number_field :profile_id, value: current_user.profile.id, type: :hidden %>
      <%= form.submit class: "btn btn-success" %>
    <% end %>
  </div>

  <br />

  <% @posts.each do |p| %>

    <%# Set a rule that you need to be friends to see each post %>
    <% if Friendship.where(user_id: p.profile.user.id).where(friend_id: current_user.id).where(confirmed: 1).present? ||
          Friendship.where(user_id: current_user.id).where(friend_id: p.profile.user.id).where(confirmed: 1).present? ||
          p.profile.id == current_user.profile.id %>

      <%# Main post %>
      <div class="card" id="<% p.id %>"> <div class="card-body" style="width: 40rem;">
        <h5 class="card-title">

          <% if p.profile.avatar.attached? %>
            <%= image_tag p.profile.avatar, size: '32', style: "border-radius: 50%;" %>
          <% else %>
            <img src="https://photo-cdn2.icons8.com/NqCtohJjuX8Rb8yuYNOO07iy9wS6FgUpDZTAmG4o35k/rs:fit:1608:1072/czM6Ly9pY29uczgu/bW9vc2UtcHJvZC5l/eHRlcm5hbC9hMmE0/Mi8yMDYzMGNmYzRk/OWY0YTMzYTVjZWZl/MWFmM2Y5MTQwZS5q/cGc.jpg" alt="Close up photo of a cat" width="32" height="32" style="border-radius: 50%;">
            <%# gravatar_image_tag( p.profile.user.email, gravatar: { size: 32 }, alt: p.profile.name, style: "border-radius: 50%;") %>
          <% end %>

          <%= link_to p.profile.name, profile_path(p.profile_id), class: "profile-link" %>
          <span class="card-subtitle mb-2 text-muted" style="font-size: 12px">
            <%= link_to p.created_at.strftime("%b %d, %Y - %l:%M %p"), p, class: "profile-link" %>
          </span>
        </h5>
        <p class="card-text" style="padding-left: 40px;"> <%= p.body %> </p>

        <%# Like Comment counter and buttons %>
        <div class="like-comment">
          <p style="font-size: 11px">
            Likes: <%= Like.where(post_id: p.id).count %>. 
            Comments: <%= Comment.where(post_id: p.id).count %>.
          </p>
          <div class="post-buttons">
            <% if Like.where(post_id: p.id).where(profile_id: current_user.profile.id).empty? %>
              <%= form_with url: "/likes" do |form| %> 
                <%= form.number_field :profile_id, value: current_user.profile.id, type: :hidden %>
                <%= form.number_field :post_id, value: p.id, type: :hidden %>
                <%= form.submit "Like", class: "btn btn-light" %>
              <% end %>
            <% else %>
              <%= button_to "Unlike", like_path(p.id), method: :delete, class: "btn btn-light"%>
            <% end %>
            <%= link_to "See comments", p, class: "btn btn-light" %>
          </div>
        </div>
      
        <%# Last comment %>
        <% if Comment.where(post_id: p.id).count > 0 %>
          <div class = "last-comment">

            <% if p.comments.last.profile.avatar.attached? %>
              <%= image_tag p.comments.last.profile.avatar, size: '15', style: "border-radius: 50%; justify-self: end;" %>
            <% else %>
              <img src="https://photo-cdn2.icons8.com/NqCtohJjuX8Rb8yuYNOO07iy9wS6FgUpDZTAmG4o35k/rs:fit:1608:1072/czM6Ly9pY29uczgu/bW9vc2UtcHJvZC5l/eHRlcm5hbC9hMmE0/Mi8yMDYzMGNmYzRk/OWY0YTMzYTVjZWZl/MWFmM2Y5MTQwZS5q/cGc.jpg" alt="Close up photo of a cat" width="15" height="15" style="border-radius: 50%; justify-self: end">
              <%# gravatar_image_tag( p.comments.last.profile.user.email, gravatar: { size: 15 }, alt: p.comments.last.profile.name, style: "border-radius: 50%; justify-self: end;") %>
            <% end %>

            <%= link_to p.comments.last.profile.name, profile_path(p.comments.last.profile.id), class: "profile-link", style: "font-size:12px;font-weight:bold;" %>
            <%= p.comments.last.body %>
          </div>
        <% end %>

        <%# Comment box %>
        <div class="comment-box">
          <b style="font-size: 12px; justify-self: end;"><%= current_user.profile.name %>: </b> 

          <%= form_with url: "/comments" do |form| %> 
            <%= form.text_field :body, placeholder: "Write a comment", class: "form-control", style: "width: fill;  border: 0 ;" %>
            <%= form.number_field :profile_id, value: current_user.profile.id, type: :hidden %>
            <%= form.number_field :post_id, value: p.id, type: :hidden %>
            <%= form.submit type: :hidden %>
          <% end %>

        </div>
      </div> </div>
    <% end %>

    <br />
  <% end %>
</div>

<br /><br />

app/views/posts/show.html.erb
<% if Friendship.where(user_id: Post.find(params[:id]).profile.user.id).where(friend_id: current_user.id).where(confirmed: 1).present? ||
      Friendship.where(user_id: current_user.id).where(friend_id: Post.find(params[:id]).profile.user.id).where(confirmed: 1).present? ||
      Post.find(params[:id]).profile.id == current_user.profile.id %>


  <div class="postshow">
    <div class="card"> <div class="card-body" style="width: 40rem;">
      <h5 class="card-title">

        <% if Post.find(params[:id]).profile.avatar.attached? %>
          <%= image_tag Post.find(params[:id]).profile.avatar, size: '32', style: "border-radius: 50%;" %>
        <% else %>
          <img src="https://photo-cdn2.icons8.com/NqCtohJjuX8Rb8yuYNOO07iy9wS6FgUpDZTAmG4o35k/rs:fit:1608:1072/czM6Ly9pY29uczgu/bW9vc2UtcHJvZC5l/eHRlcm5hbC9hMmE0/Mi8yMDYzMGNmYzRk/OWY0YTMzYTVjZWZl/MWFmM2Y5MTQwZS5q/cGc.jpg" alt="Close up photo of a cat" width="32" height="32" style="border-radius: 50%;">
          <%# gravatar_image_tag( Post.find(params[:id]).profile.user.email, gravatar: { size: 32 }, alt: Post.find(params[:id]).profile.name, style: "border-radius: 50%;") %>
        <% end %>

        <%= link_to @post.profile.name, profile_path(@post.profile_id), class: "profile-link" %>
      </h5>

      <span class="card-subtitle mb-2 text-muted" style="font-size: 12px">
        Created at: <%= @post.created_at.strftime("%b %d, %Y - %l:%M %p") %>
      </span>

      <br />
    
      <span class="card-subtitle mb-2 text-muted" style="font-size: 12px">
        Last update: <%= @post.updated_at.strftime("%b %d, %Y - %l:%M %p") %>
      </span>

      <br /><br />

      <p class="card-text"> <%= @post.body %> </p>

      <div class="like-comment">
        <p style="font-size: 11px">
          Likes: <%= Like.where(post_id: params[:id]).count %>. 
          Comments: <%= Comment.where(post_id: params[:id]).count %>.
        </p>
        <div class="post-buttons">
          <% if Like.where(post_id: params[:id]).where(profile_id: current_user.profile.id).empty? %>
            <%= form_with url: "/likes" do |form| %> 
              <%= form.number_field :profile_id, value: current_user.profile.id, type: :hidden %>
              <%= form.number_field :post_id, value: params[:id], type: :hidden %>
              <%= form.submit "Like", class: "btn btn-light" %>
            <% end %>
          <% else %>
            <%= button_to "Unlike", like_path(params[:id]), method: :delete, class: "btn btn-light"%>
          <% end %>
        </div>
      </div>


      <%# Last posts %>
      <% if Comment.where(post_id: params[:id]).count > 0 %>
        <div>
          <% Comment.where(post_id: params[:id]).each do |c| %>
            <div class = "last-comment">

              <% if c.profile.avatar.attached? %>
                <%= image_tag c.profile.avatar, size: '15', style: "border-radius: 50%; justify-self: end;" %>
              <% else %>
                <img src="https://photo-cdn2.icons8.com/NqCtohJjuX8Rb8yuYNOO07iy9wS6FgUpDZTAmG4o35k/rs:fit:1608:1072/czM6Ly9pY29uczgu/bW9vc2UtcHJvZC5l/eHRlcm5hbC9hMmE0/Mi8yMDYzMGNmYzRk/OWY0YTMzYTVjZWZl/MWFmM2Y5MTQwZS5q/cGc.jpg" alt="Close up photo of a cat" width="32" height="32" style="border-radius: 50%; justify-self: end;">
                <%# gravatar_image_tag( c.profile.user.email, gravatar: { size: 15 }, alt: c.profile.name, style: "border-radius: 50%; justify-self: end;") %>
              <% end %>


              <%= link_to c.profile.name, profile_path(c.profile_id), class: "profile-link", style: "font-size:12px;font-weight:bold;" %>
              <%= c.body %>
            </div>
          <% end %>
        </div>
      
      
      <% end %>

      <%# Comment box %>
      <div class="comment-box">
        <b style="font-size: 12px; justify-self: end;"><%= current_user.profile.name %>: </b> 

        <%= form_with url: "/comments" do |form| %> 
          <%= form.text_field :body, placeholder: "Write a comment", class: "form-control", style: "width: fill;  border: 0;" %>
          <%= form.number_field :profile_id, value: current_user.profile.id, type: :hidden %>
          <%= form.number_field :post_id, value: params[:id], type: :hidden %>
          <%= form.submit type: :hidden %>
        <% end %>
      </div>


    </div> </div>
    <br />
  </div>
<% else %>
  <h4> Hey, your not even friends!</h4>
<% end %>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <% if profile.avatar.attached? %>
    <%= image_tag profile.avatar, size: '100', style: "border-radius: 50%;" %>
  <% else %>
    <img src="https://photo-cdn2.icons8.com/NqCtohJjuX8Rb8yuYNOO07iy9wS6FgUpDZTAmG4o35k/rs:fit:1608:1072/czM6Ly9pY29uczgu/bW9vc2UtcHJvZC5l/eHRlcm5hbC9hMmE0/Mi8yMDYzMGNmYzRk/OWY0YTMzYTVjZWZl/MWFmM2Y5MTQwZS5q/cGc.jpg" alt="Close up photo of a cat" width="100" height="100" style="border-radius: 50%;">
    <%# gravatar_image_tag( Profile.find(params[:id]).user.email, gravatar: { size: 100 }, alt: Profile.find(params[:id]).name, style: "border-radius: 50%;") %>
  <% end %>


  <br/>  <br/>
  <div class="field">
    <%= form.file_field :avatar %>
  </div>

  <br/>
  <div class="field" style="width: 30rem;">
    <%= form.text_field :name, class: "form-control" %>
  </div> 
  
  <div class="field" style="width: 30rem; margin-top: 10px;">
    <%= form.text_field :interests, class: "form-control", placeholder: "How interesting are you?" %>
  </div>

  <br /> 

  <div>
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
  <p>
    <strong>Name:</strong>
    <%= profile.name %>
  </p>

</div>

app/views/profiles/edit.html.erb
<h2>Who you again?</h1>

<%= render "form", profile: @profile %>

<br>

app/views/profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Profiles</h1>

<div id="profiles">
  <% @profiles.each do |profile| %>
    <%= render profile %>
    <p>
      <%= link_to "Show this profile", profile %>
    </p>
  <% end %>
</div>

<%= link_to "New profile", new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/show.html.erb
<div class="postsindex">

  <div style="display:flex; align-items: center; gap: 20px;">
    <div>
      <% if @profile.avatar.attached? %>
        <%= image_tag @profile.avatar, size: '80', style: "border-radius: 50%;" %>
      <% else %>
        <img src="https://photo-cdn2.icons8.com/NqCtohJjuX8Rb8yuYNOO07iy9wS6FgUpDZTAmG4o35k/rs:fit:1608:1072/czM6Ly9pY29uczgu/bW9vc2UtcHJvZC5l/eHRlcm5hbC9hMmE0/Mi8yMDYzMGNmYzRk/OWY0YTMzYTVjZWZl/MWFmM2Y5MTQwZS5q/cGc.jpg" alt="Close up photo of a cat" width="80" height="80" style="border-radius: 50%;">
        <%# gravatar_image_tag( @profile.user.email, gravatar: { size: 80 }, alt: @profile.name, style: "border-radius: 50%;") %>
      <% end %>
    </div>
    <div>
      <h5>Meet and greet</h5>
      <h3><%= @profile.name %>!</h3>
      <h6>Interests: <%= @profile.interests %></h6>
    </div>
  </div>
  <%# Add a friend, accept request, cancel request, unfriend button %>
  <% unless current_user.profile.id.to_s  == params[:id].to_s %>
    <div data-turbolinks="false">

      <% unless @friends %>
        <%= form_with url: "/friendships", method: :post do |form| %>
          <%= form.number_field :friend_id, value: params[:id], type: :hidden %>
          <%= form.submit "Add friend", class: "btn btn-success" %>
        <% end %>
      <% end %>

      <% if @friends && @confirmed %> 
        <%= button_to "Unfriend button", friendship_path, method: :delete, class: "btn btn-secondary"%>
      <% end %>

      <% if @fri_inv.present? && !@confirmed %>
        <%= button_to "Accept request", friendship_path, method: :patch, class: "btn btn-success"%>
      <% end %>

      <% if @fri.present? && !@confirmed %>
        <%= button_to "Cancel request", friendship_path, method: :delete, class: "btn btn-light"%>
      <% end %>

    </div>
  <% end %>


  <%# Input field %>
  <% if current_user.profile.id.to_s  == params[:id].to_s %>
    <br />
    <div data-turbolinks="false">
      <%= form_with model: @post, class: "post-input" do |form| %> 
        <%= form.text_field :body, placeholder: "Anything brewing?", class: "form-control", style: "width: 32rem; height: 38px;" %>
        <%= form.number_field :profile_id, value: current_user.profile.id, type: :hidden %>
        <%= form.submit class: "btn btn-success" %>
      <% end %>
    </div>
  <% end %>

  <br />

  <%# Generate posts.. if you are friends %>
  <% if params[:id].to_s == current_user.profile.id.to_s || @friends && @confirmed %>

    <% @posts.each do |p| %>
      <div class="card"> <div class="card-body" style="width: 40rem;">
        <h5 class="card-title">

          <% if p.profile.avatar.attached? %>
            <%= image_tag p.profile.avatar, size: '32', style: "border-radius: 50%;" %>
          <% else %>
            <img src="https://photo-cdn2.icons8.com/NqCtohJjuX8Rb8yuYNOO07iy9wS6FgUpDZTAmG4o35k/rs:fit:1608:1072/czM6Ly9pY29uczgu/bW9vc2UtcHJvZC5l/eHRlcm5hbC9hMmE0/Mi8yMDYzMGNmYzRk/OWY0YTMzYTVjZWZl/MWFmM2Y5MTQwZS5q/cGc.jpg" alt="Close up photo of a cat" width="32" height="32" style="border-radius: 50%;">

            <%# gravatar_image_tag( p.profile.user.email, gravatar: { size: 32 }, alt: p.profile.name, style: "border-radius: 50%;") %>
          <% end %>

          <%= @profile.name %>
          <span class="card-subtitle mb-2 text-muted" style="font-size: 12px">
            <%= link_to p.created_at.strftime("%b %d, %Y - %l:%M %p"), p, class: "profile-link" %>
          </span>
        </h5>
        <p class="card-text" style="padding-left: 40px;"> <%= p.body %> </p>

        <div class="like-comment">
          <p style="font-size: 11px">
            Likes: <%= Like.where(post_id: p.id).count %>
            Comments: <%= Comment.where(post_id: p.id).count %>.
          </p>
          <div class="post-buttons">
            <% if Like.where(post_id: p.id).where(profile_id: current_user.profile.id).empty? %>
              <%= form_with url: "/likes" do |form| %> 
                <%= form.number_field :profile_id, value: current_user.profile.id, type: :hidden %>
                <%= form.number_field :post_id, value: p.id, type: :hidden %>
                <%= form.submit "Like", class: "btn btn-light" %>
              <% end %>
            <% else %>
              <%= button_to "Unlike", like_path(p.id), method: :delete, class: "btn btn-light"%>
            <% end %>
            <%= link_to "See comments", p, class: "btn btn-light" %>
          </div>
        </div>
        
        <%# Last comment %>
        <% if Comment.where(post_id: p.id).count > 0 %>
          <div class = "last-comment">

          <% if p.comments.last.profile.avatar.attached? %>
            <%= image_tag p.comments.last.profile.avatar, size: '15', style: "border-radius: 50%; justify-self: end;" %>
          <% else %>
            <img src="https://photo-cdn2.icons8.com/NqCtohJjuX8Rb8yuYNOO07iy9wS6FgUpDZTAmG4o35k/rs:fit:1608:1072/czM6Ly9pY29uczgu/bW9vc2UtcHJvZC5l/eHRlcm5hbC9hMmE0/Mi8yMDYzMGNmYzRk/OWY0YTMzYTVjZWZl/MWFmM2Y5MTQwZS5q/cGc.jpg" alt="Close up photo of a cat" width="15" height="15" style="border-radius: 50%; justify-self: end;">
            <%# gravatar_image_tag( p.comments.last.profile.user.email, gravatar: { size: 15 }, alt: Profile.find(params[:id]).name, style: "border-radius: 50%; justify-self: end;") %>
          <% end %>


            <% if params[:id].to_s == p.comments.last.profile.id.to_s %>
              <b style="font-size: 12px; justify-self: end;"><%= p.comments.last.profile.name %>: </b> 
            <% else %>
              <%= link_to p.comments.last.profile.name, profile_path(p.comments.last.profile.id), class: "profile-link", style: "font-size:12px;font-weight:bold;"%>
            <% end %>

            <%= p.comments.last.body %>
          </div>
        <% end %>

        <%# Comment box %>
        <div class="comment-box">
          <b style="font-size: 12px; justify-self: end;"><%= current_user.profile.name %>: </b> 

          <%= form_with url: "/comments" do |form| %> 
            <%= form.text_field :body, placeholder: "Write a comment", class: "form-control", style: "width: fill;  border: 0 ;" %>
            <%= form.number_field :profile_id, value: current_user.profile.id, type: :hidden %>
            <%= form.number_field :post_id, value: p.id, type: :hidden %>
            <%= form.submit type: :hidden %>
          <% end %>
        </div>

      </div> </div>
      <br />
    <% end %>
  <% end %>


</div>

<br /><br />