config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :profiles
  resources :posts
  resources :friends
  resources :friendships, only: [:create, :destroy, :update, :index]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create]

  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
    unauthenticated :user do
      root 'users/registrations#new', as: :unauthenticated_root
    end
  end

  get "/auth/google_oauth2/callback", to: "omniauth_callbacks#google"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :profile
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user

end

app/models/google_account.rb
class GoogleAccount < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :profile
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :profile

  has_many :comments
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :posts
  has_many :likes

  has_many :comments, through: :posts
  has_one_attached :avatar
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  has_many :posts, through: :profile

  has_many :friendships
  has_one :google_account

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_create do |user|
      user.name = auth.info.first_name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    
  end

  def create
    @comment = Comment.new(body: params[:body], profile_id: params[:profile_id], post_id: params[:post_id] ).save
    # redirect_back(fallback_location:"/")
    redirect_to url:"/posts##{params[:post_id]}"
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!

  def index
    @profiles = Profile.where.not(id: current_user.profile.id).shuffle
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.profile_id = params[:profile_id]
    @like.post_id = params[:post_id]
    @like.save
    redirect_back(fallback_location:"/")
  end

  def destroy
    Like.where(profile_id: current_user.profile.id).where(post_id: params[:id]).delete_all
    redirect_back(fallback_location:"/")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new
  end

  def new
    @post = current_user.posts.build
  end

  def show
    @post = Post.find(params[:id])

    
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_back(fallback_location:"/")
    else 
      flash[:notice] = "Some errors!"
      render :new, status: :unprocessable_entity
    end

  end

  private

  def post_params
    params.require(:post).permit(:body, :profile_id)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]
  before_action :authenticate_user!


  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
    @profile = Profile.find(params[:id])
    @post = Post.new
    @posts = Post.where(profile_id: params[:id]).order(created_at: :desc)

    @fri = Friendship.where(user_id: current_user.id).where(friend_id: params[:id])
    @fri_inv = Friendship.where(user_id: params[:id]).where(friend_id: current_user.id)
    @friends = true if @fri.present? || @fri_inv.present?

    fri_c = @fri.where(confirmed: 1)
    fri_inv_c = @fri_inv.where(confirmed: 1)
    @confirmed = true if fri_c.present? || fri_inv_c.present?
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:name, :interests, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>
    Made by jedtapiador@gmail.com. 
    Github: <a href="https://github.com/jedtap" target="_blank">github.com/jedtap</a>. 
    LinkedIn:<a href="https://www.linkedin.com/in/jed-tapiador" target="_blank">linkedin.com/in/jed-tapiador</a>.
  </p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #004307;">
  <div class="container-fluid">

    <% if user_signed_in? %>
      <%= link_to "Mukhabook", authenticated_root_path , class:"navbar-brand" %>
    <% else %>
      <%= link_to "Mukhabook", unauthenticated_root_path , class:"navbar-brand" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item"> <%= link_to "Find a friend", friends_path, class:"nav-link" %> </li>
          <li class="nav-item"> <%= link_to current_user.profile.name, current_user.profile , class:"nav-link"%> </li>
          <li class="nav-item">
            <% if  Friendship.where(friend_id: current_user.id).where(confirmed: 0).count > 0 %>
              <%= link_to "New friend request!", friendships_path , class:"nav-link new-friend-notif"%>
            <% elsif Friendship.where(user_id: current_user.id).where(confirmed: 0).count > 0 %>
              <%= link_to "Friend requests", friendships_path , class:"nav-link"%>
            <% else %>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Menu
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li> <%= link_to "Edit profile", edit_profile_path(current_user.profile.id), class: "dropdown-item" %> </li>
              <li> <%= link_to "Change email/password", edit_user_registration_path, class: "dropdown-item" %> </li>
              <li><hr class="dropdown-divider"></li>
              <li> <%= link_to "Sign Out",  destroy_user_session_path, method: :delete, class:"dropdown-item"%> </li>
            </ul>
          </li>
        <% end %>
      </ul>      
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Mukhabook</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="stylesheets/application.css">

  </head>
  <body>
    <%= render "layouts/header"%> 
    <br/>

    <div class="container">
      <% if notice %> <%= render "layouts/notice"%> <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
 
   <%= render "layouts/footer"%>
  </body>
</html>